language: rust
sudo: false
cache:
- apt
- cargo
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
notifications:
  slack:
    rooms:
      secure: S2Y4BXka0aLMy76mhdw2sIrGLvQnNh1hIsQOt7dMr6Zip/ddNXon4i3q66lm2DClBqQHh3PAXw+X6XYYx+fyWoKTRANl6uAH248Fj2ZyIlRSiR3qxNp/UWnnq1rcnzH5BgRpOqhF2ijqpDROZnZ47gbCex4u33WpCKeKOQrlEVQxW9EkCBQ+t2VXa7MoqgiwPRzZUAj+R9uXZ30Jn4hkxHJ6ukEfmY1yz1sOW5Cnvat0frYwyoe+gLOAPyt0Qdi6vFXFlJM5XrnMQAFLyCsMOSAe6resn7UUxHIHl50E29IlUhSaBbUyZhmlw4lQ5S8gWGd1m1AK9rifBGGZVtRgL3uSvgccxFr4LQ/ssLrpoArnaPcHd8Dq8Mnno3wGXa7won+x+TE32NugXQVDVxVVvZ+DCGpxv880APi3DVSDa8XhrPvs6T2m6ls4YlGV963o8cCbGOvjCFk/nEslu6gpx1xMRvoaj9CxiHYwIQ7zEw07Rv5ImmQ5Teb9+7aGQh1pgOWLiKMGKsIzQq6+Cb0ryn8bcmlAAZjd1ZVG9VhUS1086ksEqY95KdpAd7CtsHaMNcDjzDw7gtQOuUW7joHA0HIxIuG2KYk6NAc7IA3saN+Xto1dyBfZOjFxxAJO6mr+YNHp8ONLsFGcRTNG6l1Y8qnzwldEEPkLrU4Lto73u7Q=
